Traceback (most recent call last):
  File "/home/max/Documents/papers/ml-map/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/max/Documents/papers/ml-map/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/max/Documents/papers/ml-map/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/max/Documents/papers/ml-map/.venv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/max/Documents/papers/ml-map/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/max/Documents/papers/ml-map/.venv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import numpy as np
import sqlite3
import gzip
import json

df = pd.read_feather('data/final_dataset.feather')
df = df.fillna(0)
df['idx'] = df.index

# We need a single sector to colour code the dots, let's get the maximum
df['sector'] = df[sectors].apply(lambda x: sectors[np.argmax(x)], axis=1)

# We'll write it out in json format in 5 chunks
chunk_size = df.shape[0] // 5
for i, group in df.groupby(np.arange(len(df))//chunk_size):
    d = {x: list(group[x]) for x in df.columns}
    json_str = json.dumps(d)
    json_bytes = json_str.encode('utf-8')   
    with gzip.open(f'app/assets/data_{i}.json', 'w') as f:
        f.write(json_bytes)

# We'll also write out a database
with sqlite3.connect("app/data/data.db") as con:
    cursor = con.cursor()
    cursor.execute("DROP TABLE IF EXISTS data ")
    df.to_sql('data',con)

# And we'll write a table of just the texts
df['text'] = df['title'] + ' ' + df['abstract']
df[['idx','text']].to_feather('app/assets/texts.feather')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 12[0m
[1;32m      9[0m df[[38;5;124m'[39m[38;5;124midx[39m[38;5;124m'[39m] [38;5;241m=[39m df[38;5;241m.[39mindex
[1;32m     11[0m [38;5;66;03m# We need a single sector to colour code the dots, let's get the maximum[39;00m
[0;32m---> 12[0m df[[38;5;124m'[39m[38;5;124msector[39m[38;5;124m'[39m] [38;5;241m=[39m df[[43msectors[49m][38;5;241m.[39mapply([38;5;28;01mlambda[39;00m x: sectors[np[38;5;241m.[39margmax(x)], axis[38;5;241m=[39m[38;5;241m1[39m)
[1;32m     14[0m [38;5;66;03m# We'll write it out in json format in 5 chunks[39;00m
[1;32m     15[0m chunk_size [38;5;241m=[39m df[38;5;241m.[39mshape[[38;5;241m0[39m] [38;5;241m/[39m[38;5;241m/[39m [38;5;241m5[39m

[0;31mNameError[0m: name 'sectors' is not defined

